name: Upload to GitHub
on:
  push:
    branches:
      - master
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Setup node first
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.0.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: localPath
          username: LasyIsLazy
          repo: githubRepo
          remote-dir: remoteDir
 