on:
  schedule:
    - cron: '* * */1 * *'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: install
        run: yarn
      - name: Backup image
        uses: ./backup-img-action # Uses an action in the root directory
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
