name: UPLOAD
on:
  push:
    branches:
      - master
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: install
        run: yarn
      - name: Upload
        uses: ./upload-action
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: t1
          username: LasyIsLazy
          repo: img
          # remote-dir: /r1
 