name: UPLOAD
on:
  push:
    branches:
      - master
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: install
        run: yarn
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.0.2-beta.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: test/
          username: LasyIsLazy
          repo: img
          remote-dir: /tt1
          commit-message: upload files test
